### ISSUE TITLE
Port userscripts to the new relationship editor

### ISSUE THREAD

**Issue by kellnerd** [loujine/musicbrainz-scripts#61] opened 2023-02-02 14:20 UTC
Userscripts which will be broken by [MBS-11847 - Port the relationship editors to React](https://tickets.metabrainz.org/browse/MBS-11847):
- [x] MusicBrainz relation editor: Clone recording relations onto other recordings
- [x] MusicBrainz relation editor: Copy dates on recording relations
- [x] MusicBrainz relation editor: Guess related works in batch
- [x] MusicBrainz relation editor: Replace release relations by recording relations
- [x] MusicBrainz relation editor: set role in recording-artist relation
- [x] MusicBrainz relation editor: Set relation attributes

Let me know if you need any help with that task, as I've already tackled the new relationship editor for my own userscripts and even requested some userscript hooks to be exposed by MBS client-side code.
You can find the relevant parts of my code which automate the React relationship editor [inside this directory](https://github.com/kellnerd/musicbrainz-scripts/tree/main/src/relationship-editor). If you want, you can just copy the helper functions that you need or I could provide a bundled library script, which could be `@require`d by your userscripts.

**Comment by loujine** [comment] 2023-02-05 23:39
Thanks for the heads-up - I started looking at your repo and that helped me see how to generate and modify dialogs for release relations, I have to look at how to create recording relationships dialogs now

> even requested some userscript hooks to be exposed by MBS client-side code
I'm interested in knowing more, I will check brainzbot logs since I guessed it was discussed on IRC

**Comment by kellnerd** [comment] 2023-02-06 08:50
The relevant MBS PRs are the following: 
- https://github.com/metabrainz/musicbrainz-server/pull/2582
  (I requested `MB.relationshipEditor` to be exposed right in this initial PR)
- https://github.com/metabrainz/musicbrainz-server/pull/2671
- https://github.com/metabrainz/musicbrainz-server/pull/2733

> I have to look at how to create recording relationships dialogs now

Not sure if you even need dialogs for your use cases, you can also [create relationships directly](https://github.com/kellnerd/musicbrainz-scripts/blob/main/src/relationship-editor/createRelationship.js) without having to create a dialog now, unlike with the old relationship editor where you created a dialog but never showed it to the user.

In order to use a (single) recording as a source entity, you simply have to replace `MB.relationshipEditor.state.entity` (= the release in the release relationship editor) with the recording which you want to edit, e.g.
```js
createRelationship({ source: MB.relationshipEditor.state.entity.mediums[0].tracks[0].recording, ... })
```
If you want to create a rel for multiple recordings, you have to pass them in as [`MB.tree`](https://github.com/mwiencek/weight-balanced-tree) object:
```js
batchCreateRelationships(MB.relationshipEditor.state.selectedRecordings, ...)
```

**Comment by loujine** [comment] 2023-03-01 10:59
Pushed an update for the "convert release rels to recording rels"

**Comment by kellnerd** [comment] 2023-03-01 11:03
Thanks, I will definitely try the update.
Also, I've just turned my initial list into a checklist, feel free to edit/update it as needed.

**Comment by loujine** [comment] 2023-03-01 11:06
I just saw that, thanks

**Comment by loujine** [comment] 2023-03-03 20:40
I need to take a closer look at refactoring but working versions are on the master branch. 
Not sure why the edit note does not seem to be applied

**Comment by kellnerd** [comment] 2023-03-03 22:23
> Not sure why the edit note does not seem to be applied

React strikes again:
https://github.com/kellnerd/musicbrainz-scripts/commit/bf7da06d3cb397d2bd12fb230d9c7592b2a17f90
https://github.com/kellnerd/musicbrainz-scripts/commit/38e700956b652c9efcc13a35297e4da9e744e330

**Comment by loujine** [comment] 2023-03-06 19:50
Tests are green, I tested manually all I could think of, closing this issue

The only regression I can think of is that I didn't try to consider new pending relations for the "clone relations" script. This means if you create manually new relations, you need to save them before you can clone them to other recordings

**Closed as completed by loujine** 2023-03-06 19:50 UTC
